version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: mongoose
    versions:
    - 5.11.14
    - 5.11.15
    - 5.11.16
    - 5.11.17
    - 5.11.18
    - 5.11.19
    - 5.12.0
    - 5.12.1
    - 5.12.2
    - 5.12.3
    - 5.12.4
    - 5.12.5
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: swagger-jsdoc
    versions:
    - 6.0.1
    - 6.0.2
    - 6.0.5
    - 6.0.6
    - 6.0.7
    - 6.0.8
    - 6.0.9
  - dependency-name: chai
    versions:
    - 4.3.0
    - 4.3.1
    - 4.3.3
  - dependency-name: amqplib
    versions:
    - 0.6.0
    - 0.7.0
  - dependency-name: helmet
    versions:
    - 4.4.1
  - dependency-name: js-yaml
    versions:
    - 4.0.0
  - dependency-name: read-pkg-up
    versions:
    - 7.0.1
